#include "check.h"
#include "Decomp2Gecko/json_mini.h"

using namespace Decomp2Gecko;

TEST(json_dtk_config) {
    JsonValue document = parse_json(R"({
  "version": "1.8.3", "module_id": 0, "flag": true, "nothing": null,
  "units": [
    {"object": "build/GALE01/obj/melee/lb/lbcommand.o", "name": "melee/lb/lbcommand.c", "autogenerated": false, "code_size": 624},
    {"name": "MSL\/PPC_EABI\/critical_regions.gamecube.c"}
  ],
  "dup": 1, "dup": 2
})");
    CHECK_EQ(document.get("version")->text, std::string("1.8.3"));
    CHECK_EQ(document.get("module_id")->integer, int64_t(0));
    CHECK(document.get("flag")->boolean);
    CHECK(document.get("nothing")->kind == JsonValue::Kind::Null);
    const JsonValue* units = document.get("units");
    CHECK_EQ(units->items.size(), size_t(2));
    CHECK_EQ(units->items[1].get("name")->text, std::string("MSL/PPC_EABI/critical_regions.gamecube.c"));
    CHECK_EQ(document.get("dup")->integer, int64_t(2)); // last duplicate wins
    CHECK(document.get("absent") == nullptr);
}
